-- 트랜잭션 : 오직 DML문에 대해서만 트랜잭션을 수행할 수 있습니다(DDL문은 자동커밋)
SHOW AUTOCOMMIT; -- 오토커밋 여부 확인
SET AUTOCOMMIT ON;
SET AUTOCOMMIT OFF;

-----------------------------------------
SELECT * FROM DEPTS;
DELETE FROM DEPTS WHERE DEPARTMENT_ID = 10;
SAVEPOINT DEPT10; -- 트랜잭션의 지점
DELETE FROM DEPTS WHERE DEPARTMENT_ID = 20;
SAVEPOINT DEPT20;
DELETE FROM DEPTS WHERE DEPARTMENT_ID = 30;
-- SAVEPOINT로 돌아가기
ROLLBACK TO DEPT20;
ROLLBACK TO DEPT10;
ROLLBACK; -- 마지막 커밋이후로 돌아감

INSERT INTO DEPTS VALUES (320, 'AA', NULL, 1800);
COMMIT; -- 데이터반영